if(EXISTS "/Users/xuzihang/GitProject/GG/Serf/build_geohash/test/gorilla_test[1]_tests.cmake")
  include("/Users/xuzihang/GitProject/GG/Serf/build_geohash/test/gorilla_test[1]_tests.cmake")
else()
  add_test(gorilla_test_NOT_BUILT gorilla_test_NOT_BUILT)
endif()
