if(EXISTS "/Users/xuzihang/GitProject/GG/Serf/build_geohash/test/lz4_test[1]_tests.cmake")
  include("/Users/xuzihang/GitProject/GG/Serf/build_geohash/test/lz4_test[1]_tests.cmake")
else()
  add_test(lz4_test_NOT_BUILT lz4_test_NOT_BUILT)
endif()
