if(EXISTS "/Users/xuzihang/GitProject/GG/Serf/build_geohash/test/PerformanceProgram[1]_tests.cmake")
  include("/Users/xuzihang/GitProject/GG/Serf/build_geohash/test/PerformanceProgram[1]_tests.cmake")
else()
  add_test(PerformanceProgram_NOT_BUILT PerformanceProgram_NOT_BUILT)
endif()
