if(EXISTS "/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/elf_test[1]_tests.cmake")
  include("/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/elf_test[1]_tests.cmake")
else()
  add_test(elf_test_NOT_BUILT elf_test_NOT_BUILT)
endif()
