if(EXISTS "/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/fpc_test[1]_tests.cmake")
  include("/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/fpc_test[1]_tests.cmake")
else()
  add_test(fpc_test_NOT_BUILT fpc_test_NOT_BUILT)
endif()
