if(EXISTS "/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/lz77_test[1]_tests.cmake")
  include("/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/lz77_test[1]_tests.cmake")
else()
  add_test(lz77_test_NOT_BUILT lz77_test_NOT_BUILT)
endif()
