if(EXISTS "/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/machete_test[1]_tests.cmake")
  include("/Users/xuzihang/GitProject/GG/Serf/build_trajcompress_sp/test/machete_test[1]_tests.cmake")
else()
  add_test(machete_test_NOT_BUILT machete_test_NOT_BUILT)
endif()
